### ISSUE TITLE
Jackbox as package system?

### ISSUE THREAD

**Issue by johnnyshields** [LouHenryAlvarez/jackbox#1]
@LouHenryAlvarez firstly AWESOME library. Very glad to find someone working on modularity in Ruby (which Ruby is very painfully lacking.)

One question. What do you think about extending this to become a package system similar to what Python or EcmaScript6 have?

It might look something like this:

``` ruby
package 'some_package'
  # two different third-party libs define Foobar...
  imports :Foobar, from: 'my_lib/foobar'
  imports :Foobar, as: :OtherFoobar, from: 'other_lib/foobar'

  class MyModel
     def my_method
        Foobar.new.say 'hi''
        OtherFoobar.new.do_something_else
     end
  end

  exports MyModel
end 


# back in the global scope...

MyModel  #=> NameError: uninitialized constant MyModel

imports :MyModel, from: 'some_package'

MyModel   #=> no error
```

**Comment by LouHenryAlvarez** [comment]
@johnnyshields Interesting take on it.  

I hadn’t considered it as of yet, but it is a definite possibility.  Right now I am working on getting a new release out which will include some new enhancements and a few issue fixes.  
I will definitely study the subject and keep it mind for a future release though.

Thank you kindly.

**Comment by johnnyshields** [comment]
Cool. Such a library would theoretically enable using multiple versions of a gem within the same Ruby process--each gem in the gemfile could load it's own preferred version of each of it's deps, in a recursive fashion. Gems which are package-compliant would never have nasty Bundler version conflicts.

(This is what Node.js NPM does and it works brilliantly)

**Comment by johnnyshields** [comment]
Here are some relevant links. Looks like Cargo gem does this but looks dead (version is 0.0.3)

https://github.com/soveran/cargo

https://web.archive.org/web/20150104081749/http://andrew.ghost.io/emulating-node-js-modules-in-ruby/

Seems like Matz even tweeted about it at one point: https://twitter.com/yukihiro_matz/status/392219038195019776

**Comment by johnnyshields** [comment]
Looking at Cargo, it's 20 lines of code, seems pretty simple to do this. Maybe not needed in Jackbox...

**Comment by LouHenryAlvarez** [comment]
I don't know all the details of the Node.js package system, but I will consider it.  

Preferably I would like to focus Jackbox on the area of mix-ins.  Conceivably, we could extend that to handling of mixins stored on disk but...

Let me finish what I am doing, and I'll study the problem in more detail.

Thanks

**Comment by johnnyshields** [comment]
Yeah after seeing Cargo I think it's probably not needed in Jackbox. Better to close this issue.
